version: 2.1

jobs:
 world1:
    docker:
      - image: node:current-slim
    steps:
      - run: echo "Hello world1!"
 world2:     
    docker:
      - image: node:current-slim
    steps:
      - run: echo "Hello world"
workflows:
 hello:
   jobs:
    - world1
    - world2